# Generated by Django 5.2.8 on 2025-11-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': ('User',), 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
